version: "3"

services:
  db:
    image: postgres:14-alpine3.17
    container_name: db_app
    user: postgres
    env_file:
      - ./.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.2-alpine
    container_name: redis_app
    command: redis-server --save 20 1 --loglevel warning
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - ./data/cache/:/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: host
    image: app
    container_name: app_container
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
#    depends_on:
#      - db
#      - redis
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000

  celery_worker:
    build:
      context: .
    container_name: 'celery_worker'
    network_mode: host
    image: app
    command: celery -A config worker -l INFO
    volumes:
      - .:/app

  celery_beat:
    build:
      context: .
    container_name: 'celery_beat'
    network_mode: host
    image: app
    command: celery -A config beat -l INFO
    volumes:
      - .:/app